import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Globe } from "Component/components/ui/globe";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
       <div className="overflow-hidden">
       {children}
       
        
       </div>
      
      </body>
    </html>
  );
}
